FROM golang:1.24.2
WORKDIR /aegis
RUN mkdir -p /selfhealing/job
ADD . /aegis/
ADD bin/kubectl /usr/bin/
ADD manifests/job/* /selfhealing/job/
RUN cd /aegis && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o aegis-selfhealing cmd/aegis-selfhealing/main.go