//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AegisOpsTemplate) DeepCopyInto(out *AegisOpsTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AegisOpsTemplate.
func (in *AegisOpsTemplate) DeepCopy() *AegisOpsTemplate {
	if in == nil {
		return nil
	}
	out := new(AegisOpsTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AegisOpsTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AegisOpsTemplateList) DeepCopyInto(out *AegisOpsTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AegisOpsTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AegisOpsTemplateList.
func (in *AegisOpsTemplateList) DeepCopy() *AegisOpsTemplateList {
	if in == nil {
		return nil
	}
	out := new(AegisOpsTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AegisOpsTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AegisOpsTemplateSpec) DeepCopyInto(out *AegisOpsTemplateSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AegisOpsTemplateSpec.
func (in *AegisOpsTemplateSpec) DeepCopy() *AegisOpsTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(AegisOpsTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AegisOpsTemplateStatus) DeepCopyInto(out *AegisOpsTemplateStatus) {
	*out = *in
	out.ExecuteStatus = in.ExecuteStatus
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AegisOpsTemplateStatus.
func (in *AegisOpsTemplateStatus) DeepCopy() *AegisOpsTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(AegisOpsTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecuteStatus) DeepCopyInto(out *ExecuteStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecuteStatus.
func (in *ExecuteStatus) DeepCopy() *ExecuteStatus {
	if in == nil {
		return nil
	}
	out := new(ExecuteStatus)
	in.DeepCopyInto(out)
	return out
}
