apiVersion: aegis.io/v1alpha1
kind: AegisDiagnosis
metadata:
  name: node-diagnosis-sample
spec:
  object:
    kind: Node
    name: node-01
  timeout: "10m"
  collectorConfig:
    image: myregistry/mycustom-collector:latest
    command:
      - "/bin/bash"
      - "-c"
      - "/collector/collect.sh --section kernel --section network"
    env:
      - name: ENABLE_KERNEL_LOGS
        value: "true"
    volumeMounts:
      - name: custom-logs
        mountPath: /var/log/custom
    volumes:
      - name: custom-logs
        hostPath:
          path: /var/log/custom
