apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aegis-workflow
  resourceVersion: "2160"
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - pods/eviction
  verbs:
  - create
  - update
  - get
  - list
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - update
  - get
  - list
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - update
  - get
  - delete
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - aegis.io
  resources:
  - aegisalerts
  - aegisnodehealthchecks
  - aegisdiagnoses
  verbs:
  - create
  - delete
  - get
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-workflow
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: aegis-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aegis-workflow
subjects:
- kind: ServiceAccount
  name: aegis-workflow
  namespace: monitoring