---
apiVersion: v1
kind: Pod
metadata:
  name: {{.pod_name}}
spec:
  priorityClassName: system-node-critical
  containers:
  - image: {{.image}}
    imagePullPolicy: Always
    name: diagnose
    command:
      - diagnose
      - {{.type}}
      - {{.parameters}}
    resources:
      limits:
        cpu: 100m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 1000Mi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev
      name: dev
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  hostPID: true
  nodeName: {{.node_name}}
  restartPolicy: Never
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: dev
    hostPath:
      path: /dev
      type: Directory
