apiVersion: v1
kind: Pod
metadata:
  name: {{.pod_name}}
spec:
  priorityClassName: system-node-critical
  containers:
  - image: {{.image}}
    imagePullPolicy: Always
    name: remedy
    command:
      - /entrypoint.sh
      - remedy
      - {{.region}}
      - {{.cluster}}
      - {{.node_name}}
      - {{.action}}
    resources:
      limits:
        cpu: 100m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 1000Mi
    securityContext:
      privileged: true
    volumeMounts:
    - name: script
      mountPath: /var/selfhealing
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  hostPID: true
  nodeName: {{.node_name}}
  restartPolicy: Never
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /var/selfhealing
      type: ""
    name: script