---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{.job_name}}
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 1200
  ttlSecondsAfterFinished: 259200
  template:
    spec:
      containers:
      - image: {{.registry}}/{{.repository}}/aegis-sop:v2.0.0
        imagePullPolicy: Always
        name: reboot
        command: ["/entrypoint.sh", "reboot"]
        volumeMounts:
        - name: script
          mountPath: /var/selfhealing
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
      restartPolicy: Never
      hostNetwork: true
      hostPID: true
      nodeName: {{.node_name}}
      volumes:
      - name: script
        hostPath:
          path: /var/selfhealing
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
