//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AegisAlertCondition) DeepCopyInto(out *AegisAlertCondition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AegisAlertCondition.
func (in *AegisAlertCondition) DeepCopy() *AegisAlertCondition {
	if in == nil {
		return nil
	}
	out := new(AegisAlertCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AegisAlertOpsRule) DeepCopyInto(out *AegisAlertOpsRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AegisAlertOpsRule.
func (in *AegisAlertOpsRule) DeepCopy() *AegisAlertOpsRule {
	if in == nil {
		return nil
	}
	out := new(AegisAlertOpsRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AegisAlertOpsRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AegisAlertOpsRuleList) DeepCopyInto(out *AegisAlertOpsRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AegisAlertOpsRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AegisAlertOpsRuleList.
func (in *AegisAlertOpsRuleList) DeepCopy() *AegisAlertOpsRuleList {
	if in == nil {
		return nil
	}
	out := new(AegisAlertOpsRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AegisAlertOpsRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AegisAlertOpsRuleSpec) DeepCopyInto(out *AegisAlertOpsRuleSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.AlertConditions != nil {
		in, out := &in.AlertConditions, &out.AlertConditions
		*out = make([]AegisAlertCondition, len(*in))
		copy(*out, *in)
	}
	if in.OpsTemplate != nil {
		in, out := &in.OpsTemplate, &out.OpsTemplate
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AegisAlertOpsRuleSpec.
func (in *AegisAlertOpsRuleSpec) DeepCopy() *AegisAlertOpsRuleSpec {
	if in == nil {
		return nil
	}
	out := new(AegisAlertOpsRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AegisAlertOpsRuleStatus) DeepCopyInto(out *AegisAlertOpsRuleStatus) {
	*out = *in
	out.TriggerStatus = in.TriggerStatus
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AegisAlertOpsRuleStatus.
func (in *AegisAlertOpsRuleStatus) DeepCopy() *AegisAlertOpsRuleStatus {
	if in == nil {
		return nil
	}
	out := new(AegisAlertOpsRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerStatus) DeepCopyInto(out *TriggerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerStatus.
func (in *TriggerStatus) DeepCopy() *TriggerStatus {
	if in == nil {
		return nil
	}
	out := new(TriggerStatus)
	in.DeepCopyInto(out)
	return out
}
